### ISSUE TITLE
Support to create_function

### ISSUE THREAD

**Issue by arkadyzalko** [storesafe/cordova-sqlcipher-adapter#18]
Should be great if we can append User-defined macros like distance calculation for use with ORDER BY.

Example using iPhone SDK project: http://daveaddey.com/?p=71

**Comment by brodybits** [comment]
> Should be great if we can append User-defined macros like distance calculation for use with ORDER BY.
> 
> Example using iPhone SDK project: http://daveaddey.com/?p=71

Hi @arkadyzalko sorry for the delay and thanks for the suggestion! I have marked this idea for future consideration. It would be great for the standard version (without sqlcipher) as well.

Unfortunately it would be extremely difficult to get this kind of a feature working consistently for all supported platforms.
